import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  ShieldAlert, CheckCircle, Clock, RotateCcw, Download,
  Terminal, Search, Plus, Library, ChevronDown, Lock, ExternalLink, X
} from 'lucide-react';
import GlitchText from './GlitchText';

const BLAST_COLORS = {
  HIGH:   { color: '#ef4444', bg: 'rgba(239,68,68,0.15)', border: 'rgba(239,68,68,0.5)' },
  MEDIUM: { color: '#f59e0b', bg: 'rgba(245,158,11,0.12)', border: 'rgba(245,158,11,0.4)' },
  LOW:    { color: '#22c55e', bg: 'rgba(34,197,94,0.12)', border: 'rgba(34,197,94,0.4)' },
};

const STATUS_CONFIG = {
  EXECUTED:         { icon: CheckCircle, color: '#22c55e', label: 'EXECUTED', bg: 'rgba(34,197,94,0.1)' },
  PENDING_APPROVAL: { icon: Clock, color: '#f59e0b', label: 'PENDING APPROVAL', bg: 'rgba(245,158,11,0.1)', pulse: true },
  ROLLED_BACK:      { icon: RotateCcw, color: '#64748b', label: 'ROLLED BACK', bg: 'rgba(100,116,139,0.1)' },
};

const CATEGORIES = [
  { label: 'All Playbooks', key: 'ALL' },
  { label: 'Auto-Executed', key: 'EXECUTED' },
  { label: 'Pending Review', key: 'PENDING_APPROVAL' },
  { label: 'Rolled Back', key: 'ROLLED_BACK' },
];

export default function PlaybookExecutor({ executions = [], on_approve }) {
  const [localExecs, setLocalExecs] = useState(executions);
  const [selectedExecId, setSelectedExecId] = useState(executions[0]?.execution_id || null);
  const [expandedId, setExpandedId] = useState(null);
  const [showToast, setShowToast] = useState(null);
  const [search, setSearch] = useState('');
  const [categoryFilter, setCategoryFilter] = useState('ALL');

  // Modal State
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [newPlaybookName, setNewPlaybookName] = useState('ISOLATE_HOST');
  const [newBlastRadius, setNewBlastRadius] = useState('MEDIUM');
  const [newTargetEntity, setNewTargetEntity] = useState('AIIMS-DC-01');
  const [newPrimaryAction, setNewPrimaryAction] = useState('FIREWALL_BLOCK');
  const [newReversible, setNewReversible] = useState(true);

  useEffect(() => {
    setLocalExecs(executions);
    if (executions.length > 0 && !selectedExecId) {
      setSelectedExecId(executions[0]?.execution_id);
    }
  }, [executions]);

  const selectedExec = localExecs.find(e => e.execution_id === selectedExecId);
  const autoCount = localExecs.filter(e => e.status === 'EXECUTED' && !e.requires_approval).length;
  const pendingCount = localExecs.filter(e => e.status === 'PENDING_APPROVAL').length;
  const rolledBackCount = localExecs.filter(e => e.status === 'ROLLED_BACK').length;

  const handleApprove = async (exec_id) => {
    if (on_approve) {
      try {
        await on_approve(exec_id);
      } catch (err) {
        console.error("Backend approval failed:", err);
      }
    }
    
    // Update local state instantly for seamless feedback
    setLocalExecs(prev => prev.map(e => e.execution_id === exec_id ? {
      ...e,
      status: 'EXECUTED',
      actions: e.actions.map(act => ({ ...act, status: 'SUCCESS' })),
      audit_trail: [...e.audit_trail, { timestamp: new Date().toISOString(), action: 'Approved and executed by Administrator' }]
    } : e));

    setShowToast({ type: 'approved', id: exec_id });
    setTimeout(() => setShowToast(null), 3000);
  };

  const handleExport = () => {
    setShowToast({ type: 'export' });
    setTimeout(() => setShowToast(null), 3500);
  };

  const handleCreatePlaybook = (e) => {
    e.preventDefault();
    const newId = `exec_custom_${Math.random().toString(36).substr(2, 9)}`;
    const requiresApproval = newBlastRadius !== 'LOW';
    const status = requiresApproval ? 'PENDING_APPROVAL' : 'EXECUTED';
    
    const newExec = {
      execution_id: newId,
      playbook_name: newPlaybookName,
      status: status,
      blast_radius: newBlastRadius,
      requires_approval: requiresApproval,
      actions: [
        {
          action_type: newPrimaryAction,
          target_entity: newTargetEntity,
          status: requiresApproval ? 'PENDING' : 'SUCCESS',
          timestamp: new Date().toISOString(),
          reversible: newReversible,
          audit_log_entry: `[${new Date().toISOString()}] ACTION:${newPrimaryAction} TARGET:${newTargetEntity} STATUS:${requiresApproval ? 'PENDING' : 'SUCCESS'} BLAST_RADIUS:${newBlastRadius}`
        }
      ],
      audit_trail: [
        { timestamp: new Date().toISOString(), action: `Playbook generated by administrator. Initial status: ${status}.` }
      ]
    };

    setLocalExecs(prev => [newExec, ...prev]);
    setSelectedExecId(newId);
    setShowCreateModal(false);

    // Reset inputs
    setNewPlaybookName('ISOLATE_HOST');
    setNewBlastRadius('MEDIUM');
    setNewTargetEntity('AIIMS-DC-01');
    setNewPrimaryAction('FIREWALL_BLOCK');
    setNewReversible(true);

    setShowToast({ type: 'created' });
    setTimeout(() => setShowToast(null), 3000);
  };

  const filteredExecs = localExecs.filter(e => {
    if (categoryFilter !== 'ALL' && e.status !== categoryFilter) return false;
    if (search && !e.playbook_name?.toLowerCase().includes(search.toLowerCase())) return false;
    return true;
  });

  const counts = {
    ALL: localExecs.length,
    EXECUTED: localExecs.filter(e => e.status === 'EXECUTED').length,
    PENDING_APPROVAL: pendingCount,
    ROLLED_BACK: rolledBackCount,
  };

  return (
    <div className="flex flex-col h-full overflow-hidden relative" style={{ background: 'transparent' }}>

      {/* Toast */}
      <AnimatePresence>
        {showToast && (
          <motion.div
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            className="absolute top-0 left-1/2 -translate-x-1/2 z-50 flex items-center gap-3 px-5 py-2.5 rounded-lg border shadow-2xl"
            style={{
              background: showToast.type === 'approved' ? 'rgba(34,197,94,0.15)' : 'rgba(6,182,212,0.15)',
              borderColor: showToast.type === 'approved' ? 'rgba(34,197,94,0.5)' : 'rgba(6,182,212,0.5)',
            }}
          >
            <CheckCircle className="w-4 h-4" style={{ color: showToast.type === 'approved' ? '#22c55e' : '#06b6d4' }} />
            <span className="text-[10px] font-bold font-mono tracking-widest text-slate-200">
              {showToast.type === 'approved'
                ? 'PLAYBOOK APPROVED — EXECUTING NOW'
                : showToast.type === 'created'
                ? 'PLAYBOOK CREATED SUCCESSFULLY'
                : 'AUDIT PACKAGE EXPORTED — CRYPTOGRAPHIC HASH VALIDATED'}
            </span>
          </motion.div>
        )}
      </AnimatePresence>

      {/* ── Header ──────────────────────────────────────────────────── */}
      <div className="shrink-0 flex items-center justify-between gap-3 mb-4">
        {/* Search */}
        <div className="relative flex-1 max-w-xs">
          <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-slate-500" />
          <input
            value={search}
            onChange={e => setSearch(e.target.value)}
            placeholder="Search playbooks..."
            className="w-full pl-8 pr-3 py-1.5 text-[11px] font-mono rounded-lg border outline-none"
            style={{
              background: 'rgba(15,21,37,0.8)',
              borderColor: 'rgba(51,65,85,0.5)',
              color: '#f1f5f9',
            }}
          />
        </div>

        {/* Status filter - connected to categoryFilter state */}
        <div className="relative">
          <select
            className="appearance-none text-[10px] font-mono bg-transparent border rounded px-3 py-1.5 outline-none pr-6"
            style={{ borderColor: 'rgba(51,65,85,0.5)', color: '#94a3b8' }}
            value={categoryFilter}
            onChange={e => setCategoryFilter(e.target.value)}
          >
            <option value="ALL">ALL STATUSES</option>
            <option value="EXECUTED">EXECUTED</option>
            <option value="PENDING_APPROVAL">PENDING</option>
            <option value="ROLLED_BACK">ROLLED BACK</option>
          </select>
          <ChevronDown className="absolute right-1.5 top-1/2 -translate-y-1/2 w-3 h-3 text-slate-500 pointer-events-none" />
        </div>

        <button
          onClick={() => setShowCreateModal(true)}
          className="flex items-center gap-1.5 text-[10px] font-mono bg-cyan-950/40 text-cyan-400 border border-cyan-500/40 px-3 py-1.5 rounded hover:bg-cyan-950/70 transition-all"
        >
          <Plus className="w-3.5 h-3.5" /> CREATE PLAYBOOK
        </button>
      </div>

      <div className="flex flex-1 gap-4 overflow-hidden min-h-0">

        {/* ── Left Category Column ──────────────────────────────────── */}
        <div className="w-44 shrink-0 flex flex-col gap-1">
          {CATEGORIES.map(({ label, key }) => (
            <button
              key={key}
              onClick={() => setCategoryFilter(key)}
              className="flex items-center justify-between px-3 py-2 rounded-lg text-[11px] font-mono transition-all text-left"
              style={{
                background: categoryFilter === key ? 'rgba(6,182,212,0.1)' : 'transparent',
                color: categoryFilter === key ? '#22d3ee' : '#64748b',
                border: `1px solid ${categoryFilter === key ? 'rgba(6,182,212,0.3)' : 'transparent'}`,
              }}
            >
              <span>{label}</span>
              <span
                className="text-[9px] px-1.5 py-0.5 rounded-full font-bold"
                style={{
                  background: categoryFilter === key ? 'rgba(6,182,212,0.2)' : 'rgba(30,41,59,0.8)',
                  color: categoryFilter === key ? '#22d3ee' : '#475569',
                }}
              >
                {counts[key]}
              </span>
            </button>
          ))}

          <div className="mt-auto pt-4 border-t border-slate-800/40">
            <button className="w-full flex items-center gap-2 px-3 py-2 rounded-lg text-[10px] font-mono text-slate-500 hover:text-cyan-400 transition-colors border border-slate-800/50 hover:border-cyan-500/20">
              <ExternalLink className="w-3 h-3" />
              View All Playbooks
            </button>
          </div>
        </div>

        {/* ── Main Playbook Area ────────────────────────────────────── */}
        <div className="flex-1 overflow-y-auto space-y-3 pr-1">
          {filteredExecs.length === 0 ? (

            /* Empty state matching image 2 */
            <div className="h-full flex flex-col items-center justify-center text-center p-8 bg-slate-950/20 border border-slate-900/50 rounded-2xl relative overflow-hidden">
              <div className="absolute inset-0 pointer-events-none opacity-20 bg-[radial-gradient(circle_at_center,rgba(6,182,212,0.15)_0%,transparent_70%)]" />
              
              {/* Holographic glowing circle with book icon */}
              <div className="relative w-24 h-24 mb-6 flex items-center justify-center">
                <motion.div
                  className="absolute inset-0 rounded-full border-2 border-dashed border-cyan-500/30"
                  animate={{ rotate: 360 }}
                  transition={{ duration: 20, repeat: Infinity, ease: 'linear' }}
                />
                <motion.div
                  className="absolute inset-2 rounded-full border border-cyan-400/20"
                  animate={{ rotate: -360 }}
                  transition={{ duration: 15, repeat: Infinity, ease: 'linear' }}
                />
                <div
                  className="w-16 h-16 rounded-full flex items-center justify-center relative z-10"
                  style={{
                    background: 'radial-gradient(circle, rgba(6,182,212,0.15) 0%, rgba(6,182,212,0.02) 100%)',
                    border: '1.5px solid rgba(6,182,212,0.4)',
                    boxShadow: '0 0 20px rgba(6,182,212,0.25)',
                  }}
                >
                  <Terminal className="w-8 h-8 text-cyan-400" />
                </div>
              </div>

              <h3 className="text-sm font-bold font-mono tracking-widest text-slate-300 mb-2 uppercase">
                NO PLAYBOOKS TRIGGERED
              </h3>
              <p className="text-[10px] font-mono text-slate-500 max-w-sm mb-6 leading-relaxed">
                No playbooks have been triggered for this incident.<br />
                When response actions are recommended, they will appear here.
              </p>
              
              <button className="px-5 py-2.5 rounded-lg font-mono text-[10px] tracking-wider font-bold text-cyan-400 border border-cyan-500/40 hover:bg-cyan-500/10 transition-all duration-200">
                CREATE YOUR FIRST PLAYBOOK
              </button>
            </div>
          ) : (
            filteredExecs.map((exec, idx) => {
              const blast = BLAST_COLORS[exec.blast_radius?.toUpperCase()] || BLAST_COLORS.MEDIUM;
              const status = STATUS_CONFIG[exec.status] || STATUS_CONFIG.EXECUTED;
              const StatusIcon = status.icon;
              const isExpanded = expandedId === exec.execution_id;

              return (
                <motion.div
                  key={exec.execution_id}
                  initial={{ opacity: 0, y: 16 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: idx * 0.08, type: 'spring', stiffness: 80 }}
                  className="rounded-xl border overflow-hidden"
                  style={{
                    background: 'rgba(15,21,37,0.9)',
                    borderColor: selectedExecId === exec.execution_id
                      ? 'rgba(6,182,212,0.4)'
                      : 'rgba(51,65,85,0.4)',
                  }}
                >
                  {/* Playbook header row */}
                  <div
                    className="flex items-center gap-3 px-4 py-3 cursor-pointer"
                    onClick={() => {
                      setSelectedExecId(exec.execution_id);
                      setExpandedId(isExpanded ? null : exec.execution_id);
                    }}
                  >
                    {/* Status icon */}
                    <div
                      className="w-8 h-8 rounded-lg flex items-center justify-center shrink-0"
                      style={{ background: status.bg }}
                    >
                      <StatusIcon
                        className={`w-4 h-4 ${status.pulse ? 'animate-pulse' : ''}`}
                        style={{ color: status.color }}
                      />
                    </div>

                    {/* Name + triggered-by */}
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-0.5">
                        <span className="text-[12px] font-bold text-slate-200 font-mono truncate">
                          {exec.playbook_name}
                        </span>
                        <span
                          className="text-[8px] font-bold font-mono px-1.5 py-0.5 rounded shrink-0"
                          style={{ color: blast.color, background: blast.bg, border: `1px solid ${blast.border}` }}
                        >
                          {exec.blast_radius}
                        </span>
                      </div>
                      <span className="text-[9px] font-mono text-slate-500">
                        Triggered by: {exec.triggered_by || 'Autonomous response'} · {exec.executed_at || 'N/A'}
                      </span>
                    </div>

                    {/* Status badge */}
                    <span
                      className="text-[9px] font-bold font-mono px-2 py-1 rounded shrink-0"
                      style={{ color: status.color, background: status.bg }}
                    >
                      {status.label}
                    </span>

                    {/* Expand chevron */}
                    {isExpanded
                      ? <ChevronDown className="w-4 h-4 text-slate-500 shrink-0 rotate-180" />
                      : <ChevronDown className="w-4 h-4 text-slate-500 shrink-0" />}
                  </div>

                  {/* Expanded commands + approval */}
                  <AnimatePresence>
                    {isExpanded && (
                      <motion.div
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: 'auto', opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        className="overflow-hidden border-t"
                        style={{ borderColor: 'rgba(30,41,59,0.8)' }}
                      >
                        <div className="px-4 py-3 space-y-3">
                          {/* Commands */}
                          {exec.commands?.length > 0 && (
                            <div
                              className="rounded-lg p-3 font-mono text-[10px] space-y-1.5"
                              style={{ background: '#03050a', border: '1px solid rgba(30,41,59,0.8)' }}
                            >
                              {exec.commands.map((cmd, i) => (
                                <div key={i} className="flex gap-2 text-slate-400">
                                  <span className="text-cyan-600 select-none">{String(i + 1).padStart(2, '0')}</span>
                                  <span>{cmd}</span>
                                </div>
                              ))}
                            </div>
                          )}

                          {/* Approval buttons for PENDING */}
                          {exec.status === 'PENDING_APPROVAL' && (
                            <div className="flex gap-2">
                              <button
                                onClick={() => handleApprove(exec.execution_id)}
                                className="flex-1 py-2 rounded-lg font-bold font-mono text-[11px] tracking-widest transition-all"
                                style={{
                                  background: 'rgba(34,197,94,0.15)',
                                  border: '1px solid rgba(34,197,94,0.4)',
                                  color: '#22c55e',
                                }}
                              >
                                ✓ APPROVE EXECUTION
                              </button>
                              <button
                                className="flex-1 py-2 rounded-lg font-bold font-mono text-[11px] tracking-widest transition-all"
                                style={{
                                  background: 'rgba(239,68,68,0.1)',
                                  border: '1px solid rgba(239,68,68,0.3)',
                                  color: '#ef4444',
                                }}
                              >
                                ✕ REJECT
                              </button>
                            </div>
                          )}
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </motion.div>
              );
            })
          )}
        </div>
      </div>

      {/* ── Bottom Summary Bar (Holographic design from image 2) ────────────────── */}
      <div
        className="shrink-0 mt-4 rounded-xl border flex flex-col md:flex-row items-start md:items-center justify-between px-5 py-3.5 gap-4"
        style={{
          background: 'rgba(11,15,23,0.95)',
          borderColor: 'rgba(30,41,59,0.8)',
          boxShadow: '0 -4px 20px rgba(0,0,0,0.3)',
        }}
      >
        <div className="flex flex-col gap-1.5">
          <span className="text-[8px] font-mono text-slate-500 tracking-widest uppercase">PLAYBOOK EXECUTION SUMMARY</span>
          <div className="flex items-center gap-6">
            {[
              { label: 'AUTO-EXECUTED', value: autoCount, color: '#22c55e', symbol: '▶' },
              { label: 'PENDING', value: pendingCount, color: '#f59e0b', symbol: '📂' },
              { label: 'ROLLED BACK', value: rolledBackCount, color: '#ef4444', symbol: '↩' },
              { label: 'MANUAL EXECUTED', value: 0, color: '#06b6d4', symbol: '👤' },
            ].map(({ label, value, color, symbol }) => (
              <div key={label} className="flex items-center gap-2">
                <span className="text-[10px]" style={{ color }}>{symbol}</span>
                <span className="text-xs font-bold font-mono" style={{ color }}>{value}</span>
                <span className="text-[8px] font-mono text-slate-600 tracking-wide uppercase">{label}</span>
              </div>
            ))}
          </div>
        </div>

      </div>

      {/* Create Playbook Modal Overlay */}
      <AnimatePresence>
        {showCreateModal && (
          <div className="absolute inset-0 bg-slate-950/85 backdrop-blur-md z-50 flex items-center justify-center p-4">
            <motion.div
              initial={{ scale: 0.96, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.96, opacity: 0 }}
              className="w-full max-w-2xl rounded-2xl border p-6 flex flex-col gap-5 relative overflow-hidden"
              style={{
                background: 'rgba(10,15,26,0.98)',
                borderColor: 'rgba(6,182,212,0.3)',
                boxShadow: '0 0 50px rgba(6,182,212,0.15), inset 0 0 25px rgba(6,182,212,0.04)',
              }}
            >
              {/* Close Button */}
              <button 
                onClick={() => setShowCreateModal(false)}
                className="absolute top-5 right-5 text-slate-500 hover:text-white transition-colors"
                type="button"
              >
                <X className="w-4.5 h-4.5" />
              </button>

              {/* Modal Header */}
              <div className="flex items-center gap-2 border-b border-slate-800/80 pb-4">
                <Plus className="w-4.5 h-4.5 text-cyan-400 animate-pulse" />
                <h3 className="text-xs font-bold text-white font-mono tracking-widest uppercase">CREATE SOAR PLAYBOOK</h3>
              </div>

              <form onSubmit={handleCreatePlaybook} className="flex flex-col gap-4">
                
                {/* Playbook Name */}
                <div className="flex flex-col gap-1.5">
                  <label className="text-[9px] font-mono font-bold tracking-widest text-cyan-400/80 uppercase">
                    Playbook Name
                  </label>
                  <select
                    value={newPlaybookName}
                    onChange={(e) => {
                      setNewPlaybookName(e.target.value);
                      if (e.target.value === 'CREDENTIAL_REVOCATION') {
                        setNewBlastRadius('LOW');
                        setNewPrimaryAction('REVOKE_TOKEN');
                      } else if (e.target.value === 'ISOLATE_HOST') {
                        setNewBlastRadius('MEDIUM');
                        setNewPrimaryAction('FIREWALL_BLOCK');
                      } else if (e.target.value === 'C2_CONTAINMENT') {
                        setNewBlastRadius('HIGH');
                        setNewPrimaryAction('DNS_SINKHOLE');
                      } else if (e.target.value === 'ANTI_RANSOMWARE') {
                        setNewBlastRadius('HIGH');
                        setNewPrimaryAction('NETWORK_SEGMENT_ISOLATE');
                      }
                    }}
                    className="w-full border border-slate-800 hover:border-cyan-500/25 rounded-lg px-3.5 py-2 text-xs font-mono outline-none focus:border-cyan-500/50 focus:ring-1 focus:ring-cyan-500/30 transition-all cursor-pointer"
                    style={{ backgroundColor: '#090d16', color: '#e2e8f0' }}
                  >
                    <option value="ISOLATE_HOST" className="bg-[#090d16] text-slate-200">ISOLATE_HOST</option>
                    <option value="CREDENTIAL_REVOCATION" className="bg-[#090d16] text-slate-200">CREDENTIAL_REVOCATION</option>
                    <option value="C2_CONTAINMENT" className="bg-[#090d16] text-slate-200">C2_CONTAINMENT</option>
                    <option value="ANTI_RANSOMWARE" className="bg-[#090d16] text-slate-200">ANTI_RANSOMWARE</option>
                  </select>
                </div>

                {/* Blast Radius & Primary Action */}
                <div className="grid grid-cols-2 gap-4">
                  <div className="flex flex-col gap-1.5">
                    <label className="text-[9px] font-mono font-bold tracking-widest text-cyan-400/80 uppercase">
                      Blast Radius
                    </label>
                    <select
                      value={newBlastRadius}
                      onChange={(e) => setNewBlastRadius(e.target.value)}
                      className="w-full border border-slate-800 hover:border-cyan-500/25 rounded-lg px-3.5 py-2 text-xs font-mono outline-none focus:border-cyan-500/50 focus:ring-1 focus:ring-cyan-500/30 transition-all cursor-pointer"
                      style={{ backgroundColor: '#090d16', color: '#e2e8f0' }}
                    >
                      <option value="LOW" className="bg-[#090d16] text-slate-200">LOW (Auto-Execute)</option>
                      <option value="MEDIUM" className="bg-[#090d16] text-slate-200">MEDIUM (Requires Approval)</option>
                      <option value="HIGH" className="bg-[#090d16] text-slate-200">HIGH (Requires Approval)</option>
                    </select>
                  </div>

                  <div className="flex flex-col gap-1.5">
                    <label className="text-[9px] font-mono font-bold tracking-widest text-cyan-400/80 uppercase">
                      Primary Action
                    </label>
                    <select
                      value={newPrimaryAction}
                      onChange={(e) => setNewPrimaryAction(e.target.value)}
                      className="w-full border border-slate-800 hover:border-cyan-500/25 rounded-lg px-3.5 py-2 text-xs font-mono outline-none focus:border-cyan-500/50 focus:ring-1 focus:ring-cyan-500/30 transition-all cursor-pointer"
                      style={{ backgroundColor: '#090d16', color: '#e2e8f0' }}
                    >
                      <option value="FIREWALL_BLOCK" className="bg-[#090d16] text-slate-200">FIREWALL_BLOCK</option>
                      <option value="REVOKE_TOKEN" className="bg-[#090d16] text-slate-200">REVOKE_TOKEN</option>
                      <option value="DNS_SINKHOLE" className="bg-[#090d16] text-slate-200">DNS_SINKHOLE</option>
                      <option value="VM_SNAPSHOT" className="bg-[#090d16] text-slate-200">VM_SNAPSHOT</option>
                      <option value="NETWORK_SEGMENT_ISOLATE" className="bg-[#090d16] text-slate-200">NETWORK_SEGMENT_ISOLATE</option>
                    </select>
                  </div>
                </div>

                {/* Target Entity */}
                <div className="flex flex-col gap-1.5">
                  <label className="text-[9px] font-mono font-bold tracking-widest text-cyan-400/80 uppercase">
                    Target Entity
                  </label>
                  <input
                    type="text"
                    required
                    value={newTargetEntity}
                    onChange={(e) => setNewTargetEntity(e.target.value)}
                    placeholder="e.g. Host name, IP address, AD account"
                    className="w-full border border-slate-800 hover:border-cyan-500/25 rounded-lg px-3.5 py-2 text-xs font-mono outline-none focus:border-cyan-500/50 focus:ring-1 focus:ring-cyan-500/30 transition-all placeholder-slate-600"
                    style={{ backgroundColor: '#090d16', color: '#e2e8f0' }}
                  />
                </div>

                {/* Checkbox: Reversible */}
                <div className="flex items-center gap-2.5 py-1">
                  <input
                    type="checkbox"
                    id="reversible"
                    checked={newReversible}
                    onChange={(e) => setNewReversible(e.target.checked)}
                    className="rounded border-slate-800 bg-[#090d16] text-cyan-500 focus:ring-0 focus:ring-offset-0 w-4 h-4 cursor-pointer"
                  />
                  <label 
                    htmlFor="reversible" 
                    className="text-[10px] font-mono text-slate-400 select-none cursor-pointer hover:text-slate-300 transition-colors"
                  >
                    Support automated rollback for this playbook
                  </label>
                </div>

                {/* Form Footer Buttons */}
                <div className="flex justify-end gap-2.5 border-t border-slate-800/80 pt-4 mt-2">
                  <button
                    type="button"
                    onClick={() => setShowCreateModal(false)}
                    className="px-4 py-2 rounded-lg text-[10px] font-mono font-bold tracking-widest text-slate-400 hover:text-white hover:bg-slate-900/60 border border-transparent transition-all"
                  >
                    CANCEL
                  </button>
                  <button
                    type="submit"
                    className="px-5 py-2 rounded-lg text-[10px] font-mono font-bold tracking-widest bg-cyan-950/40 text-cyan-400 hover:bg-cyan-950/70 border border-cyan-500/40 hover:border-cyan-500/60 transition-all shadow-[0_0_15px_rgba(6,182,212,0.1)]"
                  >
                    GENERATE PLAYBOOK
                  </button>
                </div>

              </form>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
}


