// ── Simulated Threat Feed Data ────────────────────────────────────────────────
// Realistic AIIMS/CBSE context threat feed items.
// Shared between Landing "Recent Intelligence" and Tab 5 "Live Threat Feed".

export const THREAT_FEED_ITEMS = [
  {
    id: 'tf-001',
    severity: 'CRITICAL',
    headline: 'Malicious IP 185.220.101.47 Active — Tor Exit Node C2',
    description: 'Known Cobalt Strike C2 relay confirmed in AIIMS breach. Sinkhole recommended.',
    source: 'C3i Hub',
    sourceIcon: '🛡️',
    timestamp: '18:24',
    timeAgo: '2 min ago',
    ioc: '185.220.101.47',
    technique: 'T1071.001',
  },
  {
    id: 'tf-002',
    severity: 'HIGH',
    headline: 'APT41 Targeting Healthcare Sector — Active Campaign',
    description: 'Nation-state actor observed pivoting from phishing to SMB lateral movement in CNI hospitals.',
    source: 'CERT-In',
    sourceIcon: '🏛️',
    timestamp: '17:51',
    timeAgo: '35 min ago',
    ioc: 'update.microsofft.com',
    technique: 'T1078',
  },
  {
    id: 'tf-003',
    severity: 'HIGH',
    headline: 'Phishing Campaign Detected — CBSE Exam Portal Theme',
    description: 'Credential harvesting pages mimicking cbse.gov.in observed on 3 infrastructure clusters.',
    source: 'PhishTank',
    sourceIcon: '🎣',
    timestamp: '17:12',
    timeAgo: '1 hr ago',
    ioc: 'cbse-results-2026.net',
    technique: 'T1566',
  },
  {
    id: 'tf-004',
    severity: 'MEDIUM',
    headline: 'PowerShell Abuse Increasing — Fileless Execution',
    description: 'AMSI bypass variants spreading via legitimate admin tools. Detections up 340% this week.',
    source: 'VirusTotal',
    sourceIcon: '🔬',
    timestamp: '16:45',
    timeAgo: '2 hr ago',
    ioc: 'powershell -enc',
    technique: 'T1059.001',
  },
  {
    id: 'tf-005',
    severity: 'CRITICAL',
    headline: 'New Ransomware Variant — HealthLocker v2',
    description: 'Double-extortion ransomware specifically targeting HMIS and patient record systems. Uses Cobalt Strike for staging.',
    source: 'PassiveTotal',
    sourceIcon: '📡',
    timestamp: '15:30',
    timeAgo: '3 hr ago',
    ioc: 'svhost32.exe',
    technique: 'T1486',
  },
  {
    id: 'tf-006',
    severity: 'MEDIUM',
    headline: 'DNS Beaconing Pattern — 300s±45s Jitter Detected',
    description: 'Cobalt Strike DNS beacon profile matching known APT41 TTPs observed on 4 new infrastructure nodes.',
    source: 'C3i Hub',
    sourceIcon: '🛡️',
    timestamp: '14:58',
    timeAgo: '4 hr ago',
    ioc: '*.microsofft.com',
    technique: 'T1071.001',
  },
  {
    id: 'tf-007',
    severity: 'HIGH',
    headline: 'Volume Shadow Copy Deletion — 12 Endpoints',
    description: 'vssadmin delete shadows /all executed across 12 healthcare endpoints. Pre-ransomware indicator.',
    source: 'CERT-In',
    sourceIcon: '🏛️',
    timestamp: '14:20',
    timeAgo: '5 hr ago',
    ioc: 'vssadmin.exe',
    technique: 'T1490',
  },
  {
    id: 'tf-008',
    severity: 'LOW',
    headline: 'Service Account Anomaly — Off-Hours Authentication',
    description: 'svc_backup$ authenticated at 02:14 IST from external IP. Baseline deviation: 97th percentile.',
    source: 'PassiveTotal',
    sourceIcon: '📡',
    timestamp: '02:14',
    timeAgo: '16 hr ago',
    ioc: 'svc_backup$',
    technique: 'T1078',
  },
];

export const SEVERITY_CONFIG = {
  CRITICAL: { color: '#ef4444', bg: 'rgba(239,68,68,0.15)', border: 'rgba(239,68,68,0.5)', label: 'CRITICAL' },
  HIGH:     { color: '#f97316', bg: 'rgba(249,115,22,0.12)', border: 'rgba(249,115,22,0.4)', label: 'HIGH' },
  MEDIUM:   { color: '#eab308', bg: 'rgba(234,179,8,0.12)', border: 'rgba(234,179,8,0.4)', label: 'MEDIUM' },
  LOW:      { color: '#06b6d4', bg: 'rgba(6,182,212,0.10)', border: 'rgba(6,182,212,0.4)', label: 'LOW' },
};
